# Generated by Django 5.0.7 on 2024-11-02 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('FROM_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chats', to='MyApp.login')),
                ('TO_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_chats', to='MyApp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('place', models.CharField(max_length=40)),
                ('pin', models.IntegerField()),
                ('post', models.CharField(max_length=40)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('established_year', models.IntegerField()),
                ('photo', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=models.Model, to='MyApp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30)),
                ('event_details', models.CharField(max_length=400)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('event_date', models.DateField()),
                ('status', models.CharField(max_length=40)),
                ('count', models.IntegerField()),
                ('ORGANIZATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.organization')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('place', models.CharField(max_length=40)),
                ('pin', models.IntegerField()),
                ('post', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('blood_group', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='user/')),
                ('is_available', models.BooleanField(default=True)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.login')),
                ('ORGANIZATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.organization')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('EVENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.event')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='EventResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('EVENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.event')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintForEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('reply', models.TextField(default='pending')),
                ('EVENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.eventresponse')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintForApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('reply', models.TextField(default='pending')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.user')),
            ],
        ),
    ]
