# Generated by Django 5.0.7 on 2024-11-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
