# Generated by Django 5.0.7 on 2024-11-04 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackrating',
            name='EVENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.eventresponse'),
        ),
    ]
