# Generated by Django 5.0.7 on 2024-11-05 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_alter_feedbackrating_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='FROM_ID',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='TO_ID',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='status',
        ),
        migrations.AddField(
            model_name='chat',
            name='FROMID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Fromid', to='MyApp.login'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='TOID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Toid', to='MyApp.login'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.CharField(max_length=100),
        ),
    ]
